import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AppProvider } from "./providers/AppProvider";
import { Header } from "./components/header/header";

const gilroy = localFont({
  src: [
    {
      path: "./assets/fonts/Gilroy-Light.ttf",
      weight: "300",
    },
    {
      path: "./assets/fonts/Gilroy-Regular.ttf",
      weight: "400",
    },
    {
      path: "./assets/fonts/Gilroy-Medium.ttf",
      weight: "500",
    },
    {
      path: "./assets/fonts/Gilroy-Semibold.ttf",
      weight: "600",
    },
    {
      path: "./assets/fonts/Gilroy-Bold.ttf",
      weight: "700",
    },
    {
      path: "./assets/fonts/Gilroy-ExtraBold.ttf",
      weight: "900",
    },
  ],
  variable: "--font-gilroy",
});

const cassandra = localFont({
  src: [
    {
      path: "./assets/fonts/Cassandra.ttf",
      weight: "300",
    },
    {
      path: "./assets/fonts/Cassandra.ttf",
      weight: "400",
    },
  ],
  variable: "--font-cassandra",
});

export const metadata: Metadata = {
  title: "SUNFLOWER",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cassandra.variable} ${gilroy.variable} font-gilroy bg-white text-mainBlack`}
      >
        <AppProvider>
          <Header />

          {children}
        </AppProvider>
      </body>
    </html>
  );
}
