import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AppProvider } from "./providers/AppProvider";
import { Header } from "./components/header/header";

const gilroy = localFont({
  src: "./assets/fonts/Gilroy-Regular.ttf",
  variable: "--font-gilroy",
  weight: "100 300 400 500 600 900",
});

export const metadata: Metadata = {
  title: "SUNFLOWER",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${gilroy.variable} font-gilroy bg-white`}>
        <AppProvider>
          <Header />

          {children}
        </AppProvider>
      </body>
    </html>
  );
}
